version: '3'

services:
  paymentProvider:
    image: payment-provider:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROVIDER_R2DBC_URL=r2dbc:pool:postgres://host.docker.internal:5432/postgres
      - PROVIDER_R2DBC_USERNAME=postgres
      - PROVIDER_R2DBC_PASSWORD=1111
      - PROVIDER_JDBC_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - PROVIDER_JDBC_USERNAME=postgres
      - PROVIDER_JDBC_PASSWORD=1111
    deploy:
      mode: replicated
      replicas: 1