version: '1'

services:
  paymentProvider:
    image: payment-provider:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
#    environment:
#      - PROSELYTE_R2DBC_URL=r2dbc:pool:postgres://host.docker.internal:5432/postgres
#      - PROSELYTE_R2DBC_USER=postgres
#      - PROSELYTE_R2DBC_PASSWORD=1111
#      - PROSELYTE_DB_URL=jdbc:postgresql://host.docker.internal:5432/postgres
#      - PROSELYTE_DB_USER=postgres
#      - PROSELYTE_DB_PASSWORD=postgres
#      - PROSELYTE_AWS_REGION=us-east-1
#    deploy:
#      mode: replicated
#      replicas: 3